// A daily Burmese phrase for Lian to learn and say to their boyfriend. Generated by `claude -p` in the tars folder
// (text only, no tools), parsed as JSON and kept in data/state/burmese.json. One phrase per London day; `new` forces another.
const { spawn } = require('child_process');
const { TARS, burmese } = require('./store');

const TIMEOUT = 120e3;
const KEEP = 30;
let pending = null;

const londonDay = () => new Intl.DateTimeFormat('en-CA', { timeZone: 'Europe/London' }).format(new Date());

function prompt(recent) {
  const avoid = recent.length ? `\nDon't repeat any of these recent phrases: ${recent.join(' | ')}.` : '';
  return `Give Lian one short, warm, cute Burmese phrase to say to their Burmese boyfriend today — romantic, playful or sweet, the kind of thing partners actually say. Vary it day to day (compliments, "I miss you", little teases, good-morning lines, etc.).
Reply with ONLY a JSON object, no markdown or code fence:
{"burmese":"the phrase in Burmese script","phonetic":"how an English speaker pronounces it, syllable by syllable with simple respelling (not IPA), e.g. chit-teh","english":"what it means","note":"one short line: a literal gloss or when/how to say it"}${avoid}`;
}

function parse(out) {
  const i = out.indexOf('{'), j = out.lastIndexOf('}');
  if (i < 0 || j < i) throw new Error('no phrase in reply');
  const o = JSON.parse(out.slice(i, j + 1));
  for (const k of ['burmese', 'phonetic', 'english']) if (!String(o[k] || '').trim()) throw new Error('phrase missing ' + k);
  return { burmese: o.burmese.trim(), phonetic: o.phonetic.trim(), english: o.english.trim(), note: String(o.note || '').trim() };
}

function run() {
  return new Promise((resolve, reject) => {
    const doc = burmese.get();
    const recent = (doc.history || []).slice(0, 8).map(h => h.english).filter(Boolean);
    const args = ['-p', prompt(recent), '--disallowedTools', 'Edit', 'Write', 'NotebookEdit', 'Bash'];
    const child = spawn('claude', args, { cwd: TARS, stdio: ['ignore', 'pipe', 'pipe'] });
    const timer = setTimeout(() => { child.kill(); reject(new Error('timed out')); }, TIMEOUT);
    let out = '', err = '';
    child.stdout.on('data', c => { out += c; });
    child.stderr.on('data', c => { err += c; });
    child.on('error', e => { clearTimeout(timer); reject(e); });
    child.on('close', code => {
      clearTimeout(timer);
      if (code) return reject(new Error((err.trim().split('\n').pop() || `claude exited with ${code}`).slice(0, 200)));
      let phrase;
      try { phrase = parse(out); } catch (e) { return reject(e); }
      if (doc.burmese) doc.history = [{ burmese: doc.burmese, phonetic: doc.phonetic, english: doc.english, note: doc.note, date: doc.date }, ...(doc.history || [])].slice(0, KEEP);
      Object.assign(doc, phrase, { date: londonDay() });
      burmese.save();
      resolve(doc);
    });
  });
}

// Single-flight: concurrent callers share one generation.
function generate() {
  if (!pending) pending = run().finally(() => { pending = null; });
  return pending;
}

function current() {
  const doc = burmese.get();
  return { ...doc, stale: doc.date !== londonDay(), generating: !!pending };
}

module.exports = { generate, current };
